### ISSUE TITLE
(not urgent)" Who are we" text

### ISSUE THREAD

**Issue by fabioski01** [PoliTo-Rocket-Team/website#3]
The text "The people behind it are engineering students from different courses with great plans for the future." sounds odd to me, especially the part "the people behind it".
Perhaps something like "We are a group of around 20 undergraduate and graduate engineering students with great plans for the future"

**Comment by Fedesky25** [comment]
Is it better now?
> We are the newly established rocketry student team of Politecnico di Torino, entirely dedicated to the design and construction of high-powered sounding rockets, and composed by a group of around 20 undergraduate and graduate engineering students with great plans for the future.

**Comment by fabioski01** [comment]
> 

"Composed by" is not used. I would write "...dedicated to the design and construction of high-powered sounding rockets, composed of a group..."

**Comment by Fedesky25** [comment]
Fixed
