### ISSUE TITLE
(not urgent) Cavour page

### ISSUE THREAD

**Issue by fabioski01** [PoliTo-Rocket-Team/website#4]
I paste the text of Cavour's description. However, do we want to make the rocket's name public already or do we wait for the "big reveal"?

Named after Camillo Benso, Count of Cavour, one of the leading figures of the Italian Unification and the main promoter of Italy’s industrial and scientific development, Cavour is a single-stage, 2.25m long rocket with a solid COTS motor and an internal diameter of 100mm, with a variable target altitude. It is composed of three compartments and the structure is mainly made of aluminum, 3D-printed and composite materials.

Made from both COTS and in-house parts, Cavour is designed to be:

Cost-effective and durable: It is the first rocket of the Team, and it must be proven that with the least possible budget the Team is capable of manufacturing a durable rocket which can sustain a high-powered flight;

Reconfigurable: The Cavour Rocket structure design is modular, able to mount different motors, of different classes, different lengths (ranging from around 300mm to 700mm) and different diameters. It will be possible to launch the rocket with COTS motors of 38mm, 54mm and 75mm diameters. It could be possible to perform a 98mm permanent motor integration. Multiple versions of the rocket can be launched with different mission objectives, such as different apogee targets.

Reusable: The rocket is designed to safely descend with the drogue chute, after reaching the apogee, with a planned velocity of around 30 m/s, and to deploy the main parachute at the designated altitude. It is then planned to land with a velocity of approximately 5 m/s without inflicting any damage to its airframe or to the environment, so that the rocket is capable of being flown again without any major repair after just some refueling. By being a fully reusable rocket, it is capable of performing multiple launches without developing major structural damage, managing to be cheaper to operate and maintain, despite the capability of a high-powered flight. 

Cavour is the very first project of the PoliTo Rocket Team and it has completed its preliminary design phase. It will mark the beginning of rocketry at PoliTo.

**Comment by Fedesky25** [comment]
Does it go on its specific page or can it simply be on the projects page? In the former case, what do we put as brief introduction of the Cavour in the project page (on which it will be linked)?

**Comment by fabioski01** [comment]
I was thinking in its specific page. In the project page maybe just a few words on what we aim to do. 
Something like "_It's in the Team's goals to design and manufacture each year a new sounding rocket. In the future years, beside our rockets, new projects will be started to upgrade and modernize the Team's capabilities: hybrid propulsion, liquid propulsion, thrust vector control and active-fin control are just some of the Team's long-term objectives_."

**Comment by fabioski01** [comment]
text added to projects page.
