### ISSUE TITLE
PoliTo logo in sponsor page not showing in light mode

### ISSUE THREAD

**Issue by fabioski01** [PoliTo-Rocket-Team/website#8]
polito svg logo in sponsor page is white and does not show in light mode (white background)

**Comment by Fedesky25** [comment]
Unfortunately, the original svg is huge, and I'm not sure i want to embed it in the html. One option could be to make it orange: in this way there would be always enough contrast.
Furthermore, I'm tempted to put only the logo without the text on the right, since it's already written in the title.

**Comment by fabioski01** [comment]
can we reduce the size of that svg? Politecnico's guidelines for "identità visiva" forbids changing the logo colour to something other than white or blue actually. 
yeah we could use the logo without the text

**Comment by Fedesky25** [comment]
Svg isn't reducible, since it's like a code for colored path and curves, and not a jpeg or png. I'll add a background to the image, only visible in light mode.

**Comment by Fedesky25** [comment]
I solved the issue using a dark background with a pillow shape: is that fine?
